@HotelListing.API_HostAddress = https://localhost:7081

GET {{HotelListing.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing.API_HostAddress}}/api/countries

###
@id=2
GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "United States of America",
  "shortName": "USA"
}

###

PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{ 
  "countryId" : 1,
  "name": "Pakistan",
  "shortName": "PAK"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###
@id=1
GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "Pearl Harbour",
  "Address": "Texas",
  "Rating": 4.0,
  "CountryId": 2
}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  //Hotel
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###
