@HotelListing.API_HostAddress = https://localhost:7081

GET {{HotelListing.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HotelListing.API_HostAddress}}/api/countries

###
@id=2
GET {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/countries
Content-Type: application/json

{
  "name": "India",
  "shortName": "IN"
}

###

PUT {{HotelListing.API_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{ 
  "countryId" : 1,
  "name": "Pakistan",
  "shortName": "PAK"
}

###

DELETE {{HotelListing.API_HostAddress}}/api/countries/{{id}}

###

GET {{HotelListing.API_HostAddress}}/api/hotels

###
@id=1002
GET {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###

POST {{HotelListing.API_HostAddress}}/api/hotels
Content-Type: application/json

{
  "Name": "La Pino",
  "Address": "Paris",
  "Rating": 3.1,
  "CountryId": 1002
}

###

PUT {{HotelListing.API_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "Id": 1003,
  "Name": "La Pinalest",
  "Address": "Paris",
  "Rating": 3.2,
  "CountryId": 1002
}

###

DELETE {{HotelListing.API_HostAddress}}/api/hotels/{{id}}

###
